//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public string SessionKey { get; set; }
        public int Qty { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
