//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckoutCart
    {
        public int Id { get; set; }
        public int Qty { get; set; }
        public int SalesOrderID { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
